[advisories]
version = 2

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
    "MPL-2.0",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"