targets = [{ triple = "x86_64-unknown-linux-gnu" }]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "warn"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib", "Unicode-DFS-2016"]
deny = ["AGPL-3.0", "GPL-3.0", "GPL-2.0"]
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []
skip-tree = []
