# Erzwingt, dass alle crates aus vendor/ kommen.
# Verhindert "accidentally online"-Builds im CI.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

# Optional nützlich: klare Timeouts/Retry-Politik, falls "ensure-vendor" mal online muss
[net]
git-fetch-with-cli = true
retry = 1

[registries.crates-io]
protocol = "sparse"

# Offline builds can opt into the vendored snapshot by passing
# `--config source.crates-io.replace-with=vendored-sources` or by setting
# `CARGO_CONFIG` to include this file together with an override.  We keep the
# directory definition here so `cargo vendor` continues to materialise crates
# under `vendor/` without requiring additional configuration.
[source.vendored-sources]
directory = "vendor"
