name: CI
on:
  push:
  pull_request:
jobs:
  rust:
    runs-on: ubuntu-24.04
    env:
      toolchain: stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo-deny
        run: cargo deny check
      - name: test
        run: cargo test --workspace -- --nocapture
