name: security

on:
  push:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/security.yml"
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/security.yml"
  schedule:
    - cron: "17 5 * * 1"   # Mondays 05:17 UTC (weekly baseline protection)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  deny:
    name: cargo-deny (Licenses/Bans/Advisories)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          # No --disable-fetch -> keeps advisory/index data fresh
          arguments: >
            advisories
            bans
            licenses
  audit:
    name: cargo-audit (CVE-Check)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [deny]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit (fresh)
        run: cargo install cargo-audit --locked --force
      - name: Run cargo audit
        run: cargo audit --timeout 90
