name: security

on:
  push:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/security.yml"
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/security.yml"
  schedule:
    - cron: "17 5 * * 1"   # montags 05:17 UTC
  workflow_dispatch:

jobs:
  audit:
    name: Cargo security checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      # ---- cargo-deny (nutzt euer vorhandenes deny.toml) ----
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: cargo deny check (advisories + bans + sources)
        run: |
          cargo deny check advisories bans sources

      # ---- cargo-audit (ohne 'fetch'; DB wird automatisch aktualisiert) ----
      - name: Install cargo-audit (fresh)
        run: cargo install cargo-audit --locked --force
      - name: cargo audit
        run: cargo audit
